Models/ErrorViewModel.cs
using System;

namespace ShopApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShopApp.Models
{
    public class Item
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; } 
        public Shop Shop { get; set; }
        [Required]
        public int? ShopId { get; set; }
        [Required]
        public DateTime ExpiryDate { get; set; } = DateTime.UtcNow;

        public List<ItemTag> ItemTags { get; set; }

    }
}

Models/ItemTag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShopApp.Models
{
    public class ItemTag
    {
        public int ItemId { get; set; }

        public Item Item { get; set; }

        public int TagId { get; set; }

        public Tag Tag { get; set; }

        
    }
}

Models/Shop.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShopApp.Models
{
    public class Shop
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        public List<Item> Items { get; set; }
    }
}

Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShopApp.Models
{
    public class Tag
    {
        public List<ItemTag> ItemTags { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShopApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShopApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopApp.Data;
using ShopApp.Models;
using ShopApp.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShopApp.Controllers
{
    public class ItemsController : Controller
    {
        private DataContext _context;

        public ItemsController(DataContext context)
        {
            _context = context;
        }       
        public IActionResult Index()
        {
            List<Shop> itemsShop = _context.Shops.Include(c => c.Items).ToList();
            List<Item> items = _context.Items.ToList();
            return View(items);
        }
        public IActionResult Add()
        { 
            var addItem = new AddItem()
            {
                Item = new Item(),
                AllShops = _context.Shops.ToList(),
                Tags =_context.Tags.ToList(),
            };
           
            return View(addItem);
        }

        [HttpPost]
        public IActionResult Add(AddItem addItem)
        {
           if (!ModelState.IsValid)
            {
                addItem.AllShops = _context.Shops.ToList();
                return View(addItem);
            }

            _context.Items.Add(addItem.Item);
            _context.SaveChanges();

            foreach (var tagId in addItem.SelectedTagIds)
            {
                _context.ItemTags.Add(new ItemTag()
                {
                    TagId = tagId,
                    ItemId = addItem.Item.Id
                });
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var item = _context.Items.Find(id);
            _context.Items.Remove(item);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var addItem = new AddItem()
            {
                Item = _context.Items.Find(id),               
                Tags = _context.Tags.ToList(),
                AllShops = _context.Shops.ToList()
            };
            
            return View(addItem);
        }

        [HttpPost]
        public IActionResult Edit(AddItem addItem)
        {
            
            List <ItemTag> itemTags = _context.ItemTags.Where(c => c.ItemId == addItem.Item.Id).ToList();
            //_context.ItemTags.RemoveRange(itemTags);
            foreach (var item in itemTags)
            {
                _context.Remove(item);
            }
            _context.SaveChanges();
            _context.SaveChanges();
            _context.Items.Update(addItem.Item);
            _context.SaveChanges();

            foreach (var tagId in addItem.SelectedTagIds)
            {
                _context.ItemTags.Add(new ItemTag()
                {
                    TagId = tagId,
                    ItemId = addItem.Item.Id
                });
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
            
        }

    }    
}

Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopApp.Data;
using ShopApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShopApp.Controllers
{
    public class ShopController : Controller
    {
        private DataContext _context;

        public ShopController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Shop> items = _context.Shops.ToList();
            
            return View(items);
        }

        public IActionResult Add()
        {
            var shop = new Shop();
            return View(shop);
        }

        [HttpPost]
        public IActionResult Add(Shop shop)
        {
            if (!ModelState.IsValid)
            {
                return View(shop);                
            }
            _context.Shops.Add(shop);
            _context.SaveChanges();            
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var shop = _context.Items.Find(id);
            _context.Items.Remove(shop);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var shop = _context.Shops.Find(id);
            return View(shop);
        }

        [HttpPost]
        public IActionResult Edit(Shop shop)
        {
            _context.Shops.Update(shop);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
        
    
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Items/Add.cshtml
@model ShopApp.Dtos.AddItem

@using (Html.BeginForm("Add", "Items", FormMethod.Post))
{
<div class="mb-3 col-5">
            @Html.LabelFor(a => a.Item.Name)
            @Html.TextBoxFor(a => a.Item.Name)
            @Html.ValidationMessageFor(a => a.Item.Name)
</div>

 <div class="mb-3 col-5">     
            @Html.LabelFor(a => a.Item.ShopId)
            @Html.DropDownListFor(a => a.Item.ShopId, new SelectList(@Model.AllShops, "Id", "Name"))
            @Html.ValidationMessageFor(a => a.Item.ShopId)
</div>
<div class="mb-3 col-5">
            @Html.LabelFor(a => a.Tags)
            @Html.ListBoxFor(a => a.SelectedTagIds, new MultiSelectList(@Model.Tags, "Id", "Name"), new {@class = "form-control"})
            @Html.ValidationMessageFor(a => a.Tags)
 </div>


    <input type="submit" value="Submit"/>
}

Views/Items/Edit.cshtml
@model ShopApp.Dtos.AddItem

@using (Html.BeginForm("Edit", "Items", FormMethod.Post))
{
    @Html.LabelFor(a => a.Item.Name)
    @Html.TextBoxFor(a => a.Item.Name, new { @class = "form-control" })

    @Html.LabelFor(a => a.Item.ShopId)
    @Html.DropDownListFor(a => a.Item.ShopId, new SelectList(Model.AllShops, "Id", "Name"), "", new { @class = "form-control" })

    @Html.HiddenFor(m => m.Item.Id)

    @Html.LabelFor(a => a.Item.ItemTags)
    @Html.ListBoxFor(a => a.SelectedTagIds, new MultiSelectList(@Model.Tags,"Id", "Name"), new { @class = "form-control" })
    @Html.ValidationMessageFor(a => a.Item.ItemTags)
   
    <input type="submit" value="Submit"/>
}

Views/Items/Index.cshtml
@model List<Item>



<h3>Items List</h3>

<hr />
<table class="table">
    <tr>
        <th>Item Id</th>
        <th>Item Name</th>
        <th>Expiry Date</th>
        <th>Shop Name</th>        
        <th>Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.ExpiryDate</td>
            <td>@item.Shop.Name</td>

            <td>
                @Html.ActionLink("Delete", "Delete", "Items", new {id = item.Id}, new {@class = "btn btn-danger"})
                @Html.ActionLink("Edit", "Edit", "Items", new {id = item.Id}, new {@class = "btn btn-success"})
            </td>
        </tr>    
    }
    <div class="d-flex w-100 justify-content-between">
    @Html.ActionLink("Add", "Add", "Items", new {}, new {@class = "btn btn-primary"})
    </div>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Add">Add Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Items List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Shops list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Add">Add shop</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ShopApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shop/Add.cshtml
@model ShopApp.Models.Shop

@using (Html.BeginForm("Add", "Shop", FormMethod.Post))
{
<div>
            @Html.LabelFor(a => a.Name)
            @Html.TextBoxFor(a => a.Name)
            @Html.ValidationMessageFor(a => a.Name)
</div>

    <input type="submit" value="Submit"/>
}

Views/Shop/Edit.cshtml
@model ShopApp.Models.Shop

@using (Html.BeginForm("Edit", "Shop", FormMethod.Post))
{
    @Html.LabelFor(a => a.Name)
    @Html.TextBoxFor(a => a.Name)
   
    <input type="submit" value="Submit"/>
}

Views/Shop/Index.cshtml
@model List<Shop>

<h3>Shops List</h3>

<hr />
<table class="table">
    <tr>
        <th>Shop Id</th>
        <th>Shop Name</th>
        <th>Actions</th>
    </tr>
    @foreach (var shop in Model)
    {
        <tr>
            <td>@shop.Id</td>
            <td>@shop.Name</td>
            <td>                
                @Html.ActionLink("Delete", "Delete", "Shop", new {id = shop.Id}, new {@class = "btn btn-danger"})
                @Html.ActionLink("Edit", "Edit", "Shop", new {id = shop.Id}, new {@class = "btn btn-success"})
            </td>
        </tr>
    }
    <div class="d-flex w-100 justify-content-between">
    @Html.ActionLink("Add", "Add", "Shop", new {}, new {@class = "btn btn-primary"})
    </div>
</table>